service: slack-sandbox-app

provider:
  name: aws
  runtime: nodejs6.10

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  whereis:
    handler: handler.whereis
    events:
      - http: 
          path: whereis
          method: post

resources:
  Resources:
    DocumentsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: where-is
        AttributeDefinitions:
          - AttributeName: user
            AttributeType: S
        KeySchema:
          - AttributeName: user
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
