service: slack-sandbox-app

provider:
  name: aws
  apiKeys:
    - slackKey
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["WhereIsDynamoDBTable", "Arn"] }
                                
functions:
  whereis:
    handler: handler.whereis
    events:
      - http: 
          path: whereis
          method: post
          
  iamat:
    handler: handler.iamat
    events:
      - http:
          path: iamat
          method: post
          
resources:
  Resources:
    WhereIsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: where-is
        AttributeDefinitions:
          - AttributeName: user
            AttributeType: S
        KeySchema:
          - AttributeName: user
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
          